(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require Import Lia.
Require Import Psatz.
Require Import Reals.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

Axiom Q_div8 :
  forall (m:Numbers.BinNums.Z), ((ZArith.BinInt.Z.rem m 16%Z) = 0%Z) ->
  ((ZArith.BinInt.Z.rem m 8%Z) = 0%Z).

(* Why3 assumption *)
Inductive addr :=
  | addr'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> addr.
Axiom addr_WhyType : WhyType addr.
Existing Instance addr_WhyType.

(* Why3 assumption *)
Definition base (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x
  end.

(* Why3 assumption *)
Definition offset (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x1
  end.

(* Why3 assumption *)
Definition malloc := Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition null : addr := addr'mk 0%Z 0%Z.

(* Why3 assumption *)
Definition global (b:Numbers.BinNums.Z) : addr := addr'mk b 0%Z.

Parameter addr_le: addr -> addr -> Prop.

Parameter addr_lt: addr -> addr -> Prop.

Parameter addr_le_bool: addr -> addr -> Init.Datatypes.bool.

Parameter addr_lt_bool: addr -> addr -> Init.Datatypes.bool.

Axiom addr_le_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_le p q <-> ((offset p) <= (offset q))%Z.

Axiom addr_lt_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_lt p q <-> ((offset p) < (offset q))%Z.

Axiom addr_le_bool_def :
  forall (p:addr) (q:addr),
  addr_le p q <-> ((addr_le_bool p q) = Init.Datatypes.true).

Axiom addr_lt_bool_def :
  forall (p:addr) (q:addr),
  addr_lt p q <-> ((addr_lt_bool p q) = Init.Datatypes.true).

(* Why3 assumption *)
Definition shift (p:addr) (k:Numbers.BinNums.Z) : addr :=
  addr'mk (base p) ((offset p) + k)%Z.

(* Why3 assumption *)
Definition valid_rw (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  (0%Z < (base p))%Z /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_rd (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_obj (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr) :
    Prop :=
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\
  ((offset p) <= (m (base p)))%Z /\ (0%Z < (m (base p)))%Z.

(* Why3 assumption *)
Definition invalid (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (n <= 0%Z)%Z \/
  ((base p) = 0%Z) \/
  ((m (base p)) <= (offset p))%Z \/ (((offset p) + n)%Z <= 0%Z)%Z.

Axiom valid_rw_rd :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  forall (n:Numbers.BinNums.Z), valid_rw m p n -> valid_rd m p n.

Axiom valid_string :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  ((base p) < 0%Z)%Z ->
  (0%Z <= (offset p))%Z /\ ((offset p) < (m (base p)))%Z ->
  valid_rd m p 1%Z /\ ~ valid_rw m p 1%Z.

(* Why3 assumption *)
Definition included (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (0%Z < lp)%Z ->
  (0%Z <= lq)%Z /\
  ((base p) = (base q)) /\
  ((offset q) <= (offset p))%Z /\
  (((offset p) + lp)%Z <= ((offset q) + lq)%Z)%Z.

(* Why3 assumption *)
Definition separated (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (lp <= 0%Z)%Z \/
  (lq <= 0%Z)%Z \/
  ~ ((base p) = (base q)) \/
  (((offset q) + lq)%Z <= (offset p))%Z \/
  (((offset p) + lp)%Z <= (offset q))%Z.

Axiom separated_1 :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (i:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z),
  separated p lp q lq ->
  ((offset p) <= i)%Z /\ (i < ((offset p) + lp)%Z)%Z ->
  ((offset q) <= j)%Z /\ (j < ((offset q) + lq)%Z)%Z ->
  ~ ((addr'mk (base p) i) = (addr'mk (base q) j)).

Axiom separated_included :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z), (0%Z < lp)%Z ->
  (0%Z < lq)%Z -> separated p lp q lq -> ~ included p lp q lq.

Axiom included_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> included q lq r lr -> included p lp r lr.

Axiom separated_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> separated q lq r lr -> separated p lp r lr.

Axiom separated_sym :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z),
  separated p lp q lq <-> separated q lq p lp.

Parameter binit: Numbers.BinNums.Z -> Prop.

Parameter region: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter linked: (Numbers.BinNums.Z -> Numbers.BinNums.Z) -> Prop.

Parameter static_malloc: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition statically_allocated (base1:Numbers.BinNums.Z) : Prop :=
  (base1 = 0%Z) \/ (0%Z < (static_malloc base1))%Z.

Axiom valid_pointers_are_statically_allocated :
  forall (a:addr) (m:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> valid_rd m a n -> statically_allocated (base a).

Parameter int_of_addr: addr -> Numbers.BinNums.Z.

Parameter addr_of_int: Numbers.BinNums.Z -> addr.

Axiom addr_of_null : ((int_of_addr null) = 0%Z).

Axiom addr_of_int_bijection :
  forall (p:addr), statically_allocated (base p) ->
  ((addr_of_int (int_of_addr p)) = p).

Axiom table : Type.
Parameter table_WhyType : WhyType table.
Existing Instance table_WhyType.

Parameter table_of_base: Numbers.BinNums.Z -> table.

Parameter table_to_offset: table -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom table_to_offset_zero :
  forall (t:table), ((table_to_offset t 0%Z) = 0%Z).

Axiom table_to_offset_monotonic :
  forall (t:table), forall (o1:Numbers.BinNums.Z) (o2:Numbers.BinNums.Z),
  (o1 <= o2)%Z <-> ((table_to_offset t o1) <= (table_to_offset t o2))%Z.

(* Why3 assumption *)
Definition P_zeroed (Mf32:addr -> Reals.Rdefinitions.R) (a:addr)
    (b:Numbers.BinNums.Z) (e:Numbers.BinNums.Z) : Prop :=
  forall (i:Numbers.BinNums.Z), (b <= i)%Z -> (i < e)%Z ->
  ((Mf32 (shift a i)) = 0%R).

(* Why3 assumption *)
Inductive P_DotProduction: (addr -> Reals.Rdefinitions.R) -> addr -> addr ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Reals.Rdefinitions.R -> Prop :=
  | Q_P_DotProduction_dotproduction_empty_range :
      forall (Mf32:addr -> Reals.Rdefinitions.R),
      forall (a:addr) (a1:addr) (i:Numbers.BinNums.Z) (i1:Numbers.BinNums.Z)
        (i2:Numbers.BinNums.Z) (i3:Numbers.BinNums.Z) (i4:Numbers.BinNums.Z),
      (i <= 0%Z)%Z -> P_DotProduction Mf32 a a1 i i1 i2 i3 i4 0%R
  | Q_P_DotProduction_dotproduction_positive_range :
      forall (Mf32:addr -> Reals.Rdefinitions.R),
      forall (a:addr) (a1:addr) (i:Numbers.BinNums.Z) (i1:Numbers.BinNums.Z)
        (i2:Numbers.BinNums.Z) (i3:Numbers.BinNums.Z) (i4:Numbers.BinNums.Z)
        (r:Reals.Rdefinitions.R),
      let x := ((-1%Z)%Z + i)%Z in
      (0%Z < i)%Z -> P_DotProduction Mf32 a a1 x i1 i2 i3 i4 r ->
      P_DotProduction Mf32 a a1 i i1 i2 i3 i4
      (r +
       ((Mf32 (shift a (((-1%Z)%Z + i)%Z + (i1 * i2)%Z)%Z)) *
        (Mf32 (shift a1 (i3 + (i4 * x)%Z)%Z)))%R)%R.

(* Why3 assumption *)
Inductive P_RowResult: (addr -> Reals.Rdefinitions.R) -> addr -> addr ->
  addr -> Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Prop :=
  | Q_P_RowResult_rowresult_empty :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (i:Numbers.BinNums.Z) (K:Numbers.BinNums.Z)
        (N:Numbers.BinNums.Z),
      (to <= 0%Z)%Z -> P_RowResult Mf32 A B C to i K N
  | Q_P_RowResult_rowresult_step :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (i:Numbers.BinNums.Z) (K:Numbers.BinNums.Z)
        (N:Numbers.BinNums.Z),
      let x := ((-1%Z)%Z + to)%Z in
      (0%Z < to)%Z -> P_RowResult Mf32 A B C x i K N ->
      P_DotProduction Mf32 A B K i K x N
      (Mf32 (shift C (((-1%Z)%Z + to)%Z + (N * i)%Z)%Z)) ->
      P_RowResult Mf32 A B C to i K N.

(* Why3 assumption *)
Inductive P_MatrixResult: (addr -> Reals.Rdefinitions.R) -> addr -> addr ->
  addr -> Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Prop :=
  | Q_P_MatrixResult_matrixresult_empty :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (K:Numbers.BinNums.Z) (N:Numbers.BinNums.Z)
        (M:Numbers.BinNums.Z),
      (to <= 0%Z)%Z -> P_MatrixResult Mf32 A B C to K N M
  | Q_P_MatrixResult_matrixresult_step :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (K:Numbers.BinNums.Z) (N:Numbers.BinNums.Z)
        (M:Numbers.BinNums.Z),
      let x := ((-1%Z)%Z + to)%Z in
      (0%Z < to)%Z -> P_RowResult Mf32 A B C N x K N ->
      P_MatrixResult Mf32 A B C x K N M -> P_MatrixResult Mf32 A B C to K N M.

Axiom Q_dp_frame :
  forall (Mf32:addr -> Reals.Rdefinitions.R)
    (Mf321:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr)
    (to:Numbers.BinNums.Z) (i:Numbers.BinNums.Z) (K:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z) (N:Numbers.BinNums.Z) (res:Reals.Rdefinitions.R),
  (to <= K)%Z -> (0%Z <= i)%Z -> (0%Z <= j)%Z -> (j < N)%Z ->
  P_DotProduction Mf321 A B to i K j N res ->
  (forall (i1:Numbers.BinNums.Z),
   let a := shift B i1 in
   (0%Z <= i1)%Z -> (i1 < (K * N)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  (forall (i1:Numbers.BinNums.Z),
   let a := shift A i1 in
   (0%Z <= i1)%Z -> (i1 < (K * (1%Z + i)%Z)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  P_DotProduction Mf32 A B to i K j N res.

Axiom Q_mat_frame :
  forall (Mf32:addr -> Reals.Rdefinitions.R)
    (Mf321:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
    (K:Numbers.BinNums.Z) (N:Numbers.BinNums.Z) (M:Numbers.BinNums.Z)
    (to:Numbers.BinNums.Z),
  (0%Z < K)%Z -> (0%Z < N)%Z -> (to <= M)%Z ->
  P_MatrixResult Mf321 A B C to K N M ->
  (forall (i:Numbers.BinNums.Z),
   let a := shift A i in
   (0%Z <= i)%Z -> (i < (K * to)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  (forall (i:Numbers.BinNums.Z),
   let a := shift B i in
   (0%Z <= i)%Z -> (i < (K * N)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  (forall (i:Numbers.BinNums.Z),
   let a := shift C i in
   (0%Z <= i)%Z -> (i < (N * to)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  P_MatrixResult Mf32 A B C to K N M.

Axiom Q_math_bounds :
  forall (i:Numbers.BinNums.Z) (M:Numbers.BinNums.Z) (N:Numbers.BinNums.Z),
  let x := (N * i)%Z in
  (0%Z < N)%Z -> (0%Z <= i)%Z -> (i < M)%Z ->
  (0%Z <= x)%Z /\ ((N + x)%Z <= (M * N)%Z)%Z.

Axiom Q_mul_mono_nonneg :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (z:Numbers.BinNums.Z),
  (x <= y)%Z -> (0%Z <= z)%Z -> ((x * z)%Z <= (y * z)%Z)%Z.

Axiom Q_row_frame :
  forall (Mf32:addr -> Reals.Rdefinitions.R)
    (Mf321:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
    (row:Numbers.BinNums.Z) (K:Numbers.BinNums.Z) (N:Numbers.BinNums.Z)
    (to:Numbers.BinNums.Z),
  (0%Z < N)%Z -> (to <= N)%Z -> (0%Z <= row)%Z ->
  P_RowResult Mf321 A B C to row K N ->
  (forall (i:Numbers.BinNums.Z),
   let a := shift B i in
   (0%Z <= i)%Z -> (i < (K * N)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  (forall (i:Numbers.BinNums.Z),
   let a := shift A i in
   (0%Z <= i)%Z -> (i < (K * (1%Z + row)%Z)%Z)%Z -> ((Mf321 a) = (Mf32 a))) ->
  (forall (i:Numbers.BinNums.Z),
   let a := shift C (i + (N * row)%Z)%Z in
   (0%Z <= i)%Z -> (i < N)%Z -> ((Mf321 a) = (Mf32 a))) ->
  P_RowResult Mf32 A B C to row K N.

Parameter sconst: (addr -> Numbers.BinNums.Z) -> Prop.

(* Why3 assumption *)
Definition framed (m:addr -> addr) : Prop :=
  forall (p:addr), ((region (base p)) <= 0%Z)%Z ->
  ((region (base (m p))) <= 0%Z)%Z.

(* Why3 assumption *)
Definition scinit (m:addr -> Init.Datatypes.bool) : Prop :=
  forall (b:Numbers.BinNums.Z), binit b -> forall (p:addr), ((base p) = b) ->
  ((m p) = Init.Datatypes.true).

(* Why3 assumption *)
Definition eqmem {a:Type} {a_WT:WhyType a} (m1:addr -> a) (m2:addr -> a)
    (p:addr) (n:Numbers.BinNums.Z) : Prop :=
  forall (q:addr), included q 1%Z p n -> ((m1 q) = (m2 q)).

Parameter memcpy:
  forall {a:Type} {a_WT:WhyType a}, (addr -> a) -> addr -> (addr -> a) ->
  addr -> Numbers.BinNums.Z -> addr -> a.

Axiom memcpy'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (a0:addr) (m1:addr -> a) (a1:addr)
    (s:Numbers.BinNums.Z) (p:addr),
  (separated p 1%Z a0 s -> ((memcpy m0 a0 m1 a1 s p) = (m0 p))) /\
  (~ separated p 1%Z a0 s ->
   ((memcpy m0 a0 m1 a1 s p) =
    (let offset1 := (((offset a1) - (offset a0))%Z + (offset p))%Z in
     m1 (addr'mk (base a1) offset1)))).

Axiom eqmem_single :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  eqmem m1 m2 p 1%Z <-> ((m1 p) = (m2 p)).

Axiom eqmem_included :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr) (q:addr),
  forall (a1:Numbers.BinNums.Z) (b:Numbers.BinNums.Z), included p a1 q b ->
  eqmem m1 m2 q b -> eqmem m1 m2 p a1.

Axiom eqmem_sym :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  forall (a1:Numbers.BinNums.Z), eqmem m1 m2 p a1 -> eqmem m2 m1 p a1.

Axiom eqmem_update :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a), forall (v:a), forall (p:addr) (q:addr),
  forall (n':Numbers.BinNums.Z), separated p 1%Z q n' ->
  eqmem m0 (map.Map.set m0 p v) q n'.

Axiom eqmem_memcpy :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (m1:addr -> a), forall (p:addr) (p':addr) (q:addr),
  forall (n:Numbers.BinNums.Z) (n':Numbers.BinNums.Z), separated p n p' n' ->
  eqmem m0 (memcpy m0 p m1 q n) p' n'.

(* Why3 goal *)
Theorem wp_goal :
  forall (a:addr) (a1:addr) (a2:addr) (i:Numbers.BinNums.Z)
    (i1:Numbers.BinNums.Z) (t:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (t1:addr -> Reals.Rdefinitions.R) (t2:addr -> Reals.Rdefinitions.R)
    (t3:addr -> Reals.Rdefinitions.R) (t4:addr -> Reals.Rdefinitions.R)
    (i2:Numbers.BinNums.Z) (i3:Numbers.BinNums.Z) (i4:Numbers.BinNums.Z)
    (i5:Numbers.BinNums.Z),
  let x := (i2 * i3)%Z in
  let x1 := (i2 + x)%Z in
  let x2 := (i1 * i2)%Z in
  let x3 := (i * i1)%Z in
  let a3 := shift a1 0%Z in
  let x4 := (i * i2)%Z in
  let a4 := shift a 0%Z in
  let a5 := shift a2 0%Z in
  let a6 := memcpy t1 a5 t4 a5 x2 in
  let a7 := shift a2 x in
  let a8 := memcpy a6 a7 t3 a7 i2 in
  let a9 := memcpy a8 a7 t2 a7 i2 in
  ((ZArith.BinInt.Z.rem i4 8%Z) = 0%Z) ->
  ((ZArith.BinInt.Z.rem i2 16%Z) = 0%Z) -> (0%Z < i2)%Z -> (0%Z < i1)%Z ->
  (0%Z < i)%Z -> (0%Z <= i5)%Z -> (i <= i5)%Z -> (0%Z <= i4)%Z ->
  (i2 <= i4)%Z -> (0%Z <= i3)%Z -> (i3 < i1)%Z -> (i4 <= i2)%Z ->
  (i3 <= i1)%Z -> (i5 <= i)%Z -> ((region (base a2)) <= 0%Z)%Z ->
  ((region (base a1)) <= 0%Z)%Z -> ((region (base a)) <= 0%Z)%Z ->
  (x1 <= x2)%Z -> ((i + (i * i3)%Z)%Z <= x3)%Z ->
  ((i * (1%Z + i3)%Z)%Z <= x3)%Z -> linked t -> valid_rd t a3 x4 ->
  valid_rd t a4 x3 -> valid_rw t a5 x2 -> separated a3 x4 a5 x2 ->
  separated a4 x3 a5 x2 -> P_MatrixResult t1 a a1 a2 0%Z i i2 i1 ->
  P_zeroed a6 a2 x x -> P_MatrixResult a6 a a1 a2 i3 i i2 i1 ->
  P_zeroed a8 a2 x (i4 + x)%Z -> P_zeroed a8 a2 x x1 ->
  (forall (i6:Numbers.BinNums.Z), (0%Z <= i6)%Z -> (i6 < i2)%Z ->
   P_DotProduction a8 a a1 0%Z i3 i i6 i2 (a8 (shift a2 (i6 + x)%Z))) ->
  (forall (i6:Numbers.BinNums.Z), (0%Z <= i6)%Z -> (i6 < i2)%Z ->
   P_DotProduction a9 a a1 i5 i3 i i6 i2 (a9 (shift a2 (i6 + x)%Z))) ->
  P_RowResult a9 a a1 a2 i2 i3 i i2.
Proof.
intros a a1 a2 i i1 t t1 t2 t3 t4 i2 i3 i4 i5 x x1 x2 x3 a3 x4 a4 a5 a6 a7 a8
a9 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17 h18 h19 h20 h21
h22 h23 h24 h25 h26 h27 h28 h29 h30 h31 h32 h33.

assert (Hi5eq: i5 = i) by lia.
rewrite Hi5eq in h33.

assert (H_row: forall n:nat, (Z.of_nat n <= i2)%Z ->
                P_RowResult a9 a a1 a2 (Z.of_nat n) i3 i i2).
{ induction n as [|n' IHn]; intros Hbnd.
  - apply Q_P_RowResult_rowresult_empty. lia.
  - apply Q_P_RowResult_rowresult_step.
    + lia.
    + replace ((- (1))%Z + Z.of_nat (S n'))%Z with (Z.of_nat n') by (rewrite Nat2Z.inj_succ; lia).
      apply IHn. lia.
    + replace ((- (1))%Z + Z.of_nat (S n'))%Z with (Z.of_nat n') by (rewrite Nat2Z.inj_succ; lia).
      apply h33; lia.
}

assert (Hfin := H_row (Z.to_nat i2) ltac:(rewrite Z2Nat.id; lia)).
rewrite Z2Nat.id in Hfin by lia.
exact Hfin.
Qed.

