(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

Axiom Q_math_bounds :
  forall (i:Numbers.BinNums.Z) (M:Numbers.BinNums.Z) (N:Numbers.BinNums.Z),
  let x := (N * i)%Z in
  (0%Z < N)%Z -> (0%Z <= i)%Z -> (i < M)%Z ->
  (0%Z <= x)%Z /\ ((N + x)%Z <= (M * N)%Z)%Z.

(* Why3 assumption *)
Inductive addr :=
  | addr'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> addr.
Axiom addr_WhyType : WhyType addr.
Existing Instance addr_WhyType.

(* Why3 assumption *)
Definition base (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x
  end.

(* Why3 assumption *)
Definition offset (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x1
  end.

(* Why3 assumption *)
Definition malloc := Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition null : addr := addr'mk 0%Z 0%Z.

(* Why3 assumption *)
Definition global (b:Numbers.BinNums.Z) : addr := addr'mk b 0%Z.

Parameter addr_le: addr -> addr -> Prop.

Parameter addr_lt: addr -> addr -> Prop.

Parameter addr_le_bool: addr -> addr -> Init.Datatypes.bool.

Parameter addr_lt_bool: addr -> addr -> Init.Datatypes.bool.

Axiom addr_le_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_le p q <-> ((offset p) <= (offset q))%Z.

Axiom addr_lt_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_lt p q <-> ((offset p) < (offset q))%Z.

Axiom addr_le_bool_def :
  forall (p:addr) (q:addr),
  addr_le p q <-> ((addr_le_bool p q) = Init.Datatypes.true).

Axiom addr_lt_bool_def :
  forall (p:addr) (q:addr),
  addr_lt p q <-> ((addr_lt_bool p q) = Init.Datatypes.true).

(* Why3 assumption *)
Definition shift (p:addr) (k:Numbers.BinNums.Z) : addr :=
  addr'mk (base p) ((offset p) + k)%Z.

(* Why3 assumption *)
Definition valid_rw (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  (0%Z < (base p))%Z /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_rd (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_obj (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr) :
    Prop :=
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\
  ((offset p) <= (m (base p)))%Z /\ (0%Z < (m (base p)))%Z.

(* Why3 assumption *)
Definition invalid (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (n <= 0%Z)%Z \/
  ((base p) = 0%Z) \/
  ((m (base p)) <= (offset p))%Z \/ (((offset p) + n)%Z <= 0%Z)%Z.

Axiom valid_rw_rd :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  forall (n:Numbers.BinNums.Z), valid_rw m p n -> valid_rd m p n.

Axiom valid_string :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  ((base p) < 0%Z)%Z ->
  (0%Z <= (offset p))%Z /\ ((offset p) < (m (base p)))%Z ->
  valid_rd m p 1%Z /\ ~ valid_rw m p 1%Z.

(* Why3 assumption *)
Definition included (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (0%Z < lp)%Z ->
  (0%Z <= lq)%Z /\
  ((base p) = (base q)) /\
  ((offset q) <= (offset p))%Z /\
  (((offset p) + lp)%Z <= ((offset q) + lq)%Z)%Z.

(* Why3 assumption *)
Definition separated (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (lp <= 0%Z)%Z \/
  (lq <= 0%Z)%Z \/
  ~ ((base p) = (base q)) \/
  (((offset q) + lq)%Z <= (offset p))%Z \/
  (((offset p) + lp)%Z <= (offset q))%Z.

Axiom separated_1 :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (i:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z),
  separated p lp q lq ->
  ((offset p) <= i)%Z /\ (i < ((offset p) + lp)%Z)%Z ->
  ((offset q) <= j)%Z /\ (j < ((offset q) + lq)%Z)%Z ->
  ~ ((addr'mk (base p) i) = (addr'mk (base q) j)).

Axiom separated_included :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z), (0%Z < lp)%Z ->
  (0%Z < lq)%Z -> separated p lp q lq -> ~ included p lp q lq.

Axiom included_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> included q lq r lr -> included p lp r lr.

Axiom separated_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> separated q lq r lr -> separated p lp r lr.

Axiom separated_sym :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z),
  separated p lp q lq <-> separated q lq p lp.

Parameter binit: Numbers.BinNums.Z -> Prop.

Parameter region: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter linked: (Numbers.BinNums.Z -> Numbers.BinNums.Z) -> Prop.

Parameter static_malloc: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition statically_allocated (base1:Numbers.BinNums.Z) : Prop :=
  (base1 = 0%Z) \/ (0%Z < (static_malloc base1))%Z.

Axiom valid_pointers_are_statically_allocated :
  forall (a:addr) (m:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> valid_rd m a n -> statically_allocated (base a).

Parameter int_of_addr: addr -> Numbers.BinNums.Z.

Parameter addr_of_int: Numbers.BinNums.Z -> addr.

Axiom addr_of_null : ((int_of_addr null) = 0%Z).

Axiom addr_of_int_bijection :
  forall (p:addr), statically_allocated (base p) ->
  ((addr_of_int (int_of_addr p)) = p).

Axiom table : Type.
Parameter table_WhyType : WhyType table.
Existing Instance table_WhyType.

Parameter table_of_base: Numbers.BinNums.Z -> table.

Parameter table_to_offset: table -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom table_to_offset_zero :
  forall (t:table), ((table_to_offset t 0%Z) = 0%Z).

Axiom table_to_offset_monotonic :
  forall (t:table), forall (o1:Numbers.BinNums.Z) (o2:Numbers.BinNums.Z),
  (o1 <= o2)%Z <-> ((table_to_offset t o1) <= (table_to_offset t o2))%Z.

(* Why3 assumption *)
Inductive P_zeroed: (addr -> Reals.Rdefinitions.R) -> addr ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Prop :=
  | Q_P_zeroed_zeroed_empty :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (a:addr)
        (b:Numbers.BinNums.Z) (e:Numbers.BinNums.Z),
      (e <= b)%Z -> P_zeroed Mf32 a b e
  | Q_P_zeroed_zeroed_range :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (a:addr)
        (b:Numbers.BinNums.Z) (e:Numbers.BinNums.Z),
      let x := ((-1%Z)%Z + e)%Z in
      ((Mf32 (shift a x)) = 0%R) -> (b < e)%Z -> P_zeroed Mf32 a b x ->
      P_zeroed Mf32 a b e.

(* Why3 assumption *)
Inductive P_DotProduction: (addr -> Reals.Rdefinitions.R) -> addr -> addr ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Reals.Rdefinitions.R -> Prop :=
  | Q_P_DotProduction_dotproduction_empty_range :
      forall (Mf32:addr -> Reals.Rdefinitions.R),
      forall (a:addr) (a1:addr) (i:Numbers.BinNums.Z) (i1:Numbers.BinNums.Z)
        (i2:Numbers.BinNums.Z) (i3:Numbers.BinNums.Z) (i4:Numbers.BinNums.Z),
      (i <= 0%Z)%Z -> P_DotProduction Mf32 a a1 i i1 i2 i3 i4 0%R
  | Q_P_DotProduction_dotproduction_positive_range :
      forall (Mf32:addr -> Reals.Rdefinitions.R),
      forall (a:addr) (a1:addr) (i:Numbers.BinNums.Z) (i1:Numbers.BinNums.Z)
        (i2:Numbers.BinNums.Z) (i3:Numbers.BinNums.Z) (i4:Numbers.BinNums.Z)
        (r:Reals.Rdefinitions.R),
      let x := ((-1%Z)%Z + i)%Z in
      (0%Z < i)%Z -> P_DotProduction Mf32 a a1 x i1 i2 i3 i4 r ->
      P_DotProduction Mf32 a a1 i i1 i2 i3 i4
      (r +
       ((Mf32 (shift a (((-1%Z)%Z + i)%Z + (i1 * i2)%Z)%Z)) *
        (Mf32 (shift a1 (i3 + (i4 * x)%Z)%Z)))%R)%R.

(* Why3 assumption *)
Inductive P_RowResult: (addr -> Reals.Rdefinitions.R) -> addr -> addr ->
  addr -> Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Prop :=
  | Q_P_RowResult_rowresult_empty :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (i:Numbers.BinNums.Z) (K:Numbers.BinNums.Z)
        (N:Numbers.BinNums.Z),
      (to <= 0%Z)%Z -> P_RowResult Mf32 A B C to i K N
  | Q_P_RowResult_rowresult_step :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (i:Numbers.BinNums.Z) (K:Numbers.BinNums.Z)
        (N:Numbers.BinNums.Z),
      let x := ((-1%Z)%Z + to)%Z in
      (0%Z < to)%Z -> P_RowResult Mf32 A B C x i K N ->
      P_DotProduction Mf32 A B K i K x N
      (Mf32 (shift C (((-1%Z)%Z + to)%Z + (N * i)%Z)%Z)) ->
      P_RowResult Mf32 A B C to i K N.

(* Why3 assumption *)
Inductive P_MatrixResult: (addr -> Reals.Rdefinitions.R) -> addr -> addr ->
  addr -> Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Prop :=
  | Q_P_MatrixResult_matrixresult_empty :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (K:Numbers.BinNums.Z) (N:Numbers.BinNums.Z)
        (M:Numbers.BinNums.Z),
      (to <= 0%Z)%Z -> P_MatrixResult Mf32 A B C to K N M
  | Q_P_MatrixResult_matrixresult_step :
      forall (Mf32:addr -> Reals.Rdefinitions.R) (A:addr) (B:addr) (C:addr)
        (to:Numbers.BinNums.Z) (K:Numbers.BinNums.Z) (N:Numbers.BinNums.Z)
        (M:Numbers.BinNums.Z),
      let x := ((-1%Z)%Z + to)%Z in
      (0%Z < to)%Z -> P_RowResult Mf32 A B C N x K N ->
      P_MatrixResult Mf32 A B C x K N M -> P_MatrixResult Mf32 A B C to K N M.

Parameter sconst: (addr -> Numbers.BinNums.Z) -> Prop.

(* Why3 assumption *)
Definition framed (m:addr -> addr) : Prop :=
  forall (p:addr), ((region (base p)) <= 0%Z)%Z ->
  ((region (base (m p))) <= 0%Z)%Z.

(* Why3 assumption *)
Definition scinit (m:addr -> Init.Datatypes.bool) : Prop :=
  forall (b:Numbers.BinNums.Z), binit b -> forall (p:addr), ((base p) = b) ->
  ((m p) = Init.Datatypes.true).

(* Why3 assumption *)
Definition eqmem {a:Type} {a_WT:WhyType a} (m1:addr -> a) (m2:addr -> a)
    (p:addr) (n:Numbers.BinNums.Z) : Prop :=
  forall (q:addr), included q 1%Z p n -> ((m1 q) = (m2 q)).

Parameter memcpy:
  forall {a:Type} {a_WT:WhyType a}, (addr -> a) -> addr -> (addr -> a) ->
  addr -> Numbers.BinNums.Z -> addr -> a.

Axiom memcpy'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (a0:addr) (m1:addr -> a) (a1:addr)
    (s:Numbers.BinNums.Z) (p:addr),
  (separated p 1%Z a0 s -> ((memcpy m0 a0 m1 a1 s p) = (m0 p))) /\
  (~ separated p 1%Z a0 s ->
   ((memcpy m0 a0 m1 a1 s p) =
    (let offset1 := (((offset a1) - (offset a0))%Z + (offset p))%Z in
     m1 (addr'mk (base a1) offset1)))).

Axiom eqmem_single :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  eqmem m1 m2 p 1%Z <-> ((m1 p) = (m2 p)).

Axiom eqmem_included :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr) (q:addr),
  forall (a1:Numbers.BinNums.Z) (b:Numbers.BinNums.Z), included p a1 q b ->
  eqmem m1 m2 q b -> eqmem m1 m2 p a1.

Axiom eqmem_sym :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  forall (a1:Numbers.BinNums.Z), eqmem m1 m2 p a1 -> eqmem m2 m1 p a1.

Axiom eqmem_update :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a), forall (v:a), forall (p:addr) (q:addr),
  forall (n':Numbers.BinNums.Z), separated p 1%Z q n' ->
  eqmem m0 (map.Map.set m0 p v) q n'.

Axiom eqmem_memcpy :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (m1:addr -> a), forall (p:addr) (p':addr) (q:addr),
  forall (n:Numbers.BinNums.Z) (n':Numbers.BinNums.Z), separated p n p' n' ->
  eqmem m0 (memcpy m0 p m1 q n) p' n'.

(* Why3 goal *)
Theorem wp_goal :
  forall (a:addr) (a1:addr) (a2:addr) (i:Numbers.BinNums.Z)
    (i1:Numbers.BinNums.Z) (t:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (t1:addr -> Reals.Rdefinitions.R) (t2:addr -> Reals.Rdefinitions.R)
    (t3:addr -> Reals.Rdefinitions.R) (t4:addr -> Reals.Rdefinitions.R)
    (i2:Numbers.BinNums.Z) (i3:Numbers.BinNums.Z) (i4:Numbers.BinNums.Z)
    (i5:Numbers.BinNums.Z),
  let a3 := shift a1 0%Z in
  let x := (i * i2)%Z in
  let a4 := shift a 0%Z in
  let x1 := (i * i1)%Z in
  let a5 := shift a2 0%Z in
  let x2 := (i1 * i2)%Z in
  let a6 := memcpy t1 a5 t4 a5 x2 in
  let x3 := (i2 * i3)%Z in
  let a7 := shift a2 x3 in
  let a8 := memcpy a6 a7 t3 a7 i2 in
  let a9 := memcpy a8 a7 t2 a7 i2 in
  (0%Z < i2)%Z -> (0%Z < i1)%Z -> (0%Z < i)%Z -> (0%Z <= i5)%Z ->
  (i <= i5)%Z -> (0%Z <= i4)%Z -> (i2 <= i4)%Z -> (0%Z <= i3)%Z ->
  (i3 < i1)%Z -> (i4 <= i2)%Z -> (i3 <= i1)%Z -> (i5 <= i)%Z ->
  ((region (base a2)) <= 0%Z)%Z -> ((region (base a1)) <= 0%Z)%Z ->
  ((region (base a)) <= 0%Z)%Z -> linked t -> valid_rd t a3 x ->
  valid_rd t a4 x1 -> valid_rw t a5 x2 -> separated a3 x a5 x2 ->
  separated a4 x1 a5 x2 -> P_MatrixResult t1 a a1 a2 0%Z i i2 i1 ->
  P_zeroed a6 a2 x3 x3 -> P_MatrixResult a6 a a1 a2 i3 i i2 i1 ->
  P_zeroed a8 a2 x3 (i4 + x3)%Z -> P_zeroed a8 a2 x3 (i2 + x3)%Z ->
  P_RowResult a9 a a1 a2 i2 i3 i i2 ->
  (forall (i6:Numbers.BinNums.Z), (0%Z <= i6)%Z -> (i6 < i2)%Z ->
   P_DotProduction a8 a a1 0%Z i3 i i6 i2 (a8 (shift a2 (i6 + x3)%Z))) ->
  (forall (i6:Numbers.BinNums.Z), (0%Z <= i6)%Z -> (i6 < i2)%Z ->
   P_DotProduction a9 a a1 i5 i3 i i6 i2 (a9 (shift a2 (i6 + x3)%Z))) ->
  P_MatrixResult a9 a a1 a2 (1%Z + i3)%Z i i2 i1.
(* Why3 intros a a1 a2 i i1 t t1 t2 t3 t4 i2 i3 i4 i5 a3 x a4 x1 a5 x2 a6 x3
        a7 a8 a9 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17
        h18 h19 h20 h21 h22 h23 h24 h25 h26 h27 h28 h29. *)
Require Import Psatz.
Proof.
intros a a1 a2 i i1 t t1 t2 t3 t4 i2 i3 i4 i5 a3 x a4 x1 a5 x2 a6 x3 a7 a8
a9 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17 h18 h19 h20
h21 h22 h23 h24 h25 h26 h27 h28 h29.

remember a9 as A9 eqn:HA9.

assert (Hincl: included a7 i2 a5 x2).
{
  unfold included, a7, a5.
  intro Hpos.
  repeat split; try reflexivity; simpl; nia.
}

assert (HsepB: separated a7 i2 a3 x).
{
  apply separated_trans with (q := a5) (lq := x2).
  - exact Hincl.
  - apply separated_sym. exact h20.
}
assert (HsepA: separated a7 i2 a4 x1).
{
  apply separated_trans with (q := a5) (lq := x2).
  - exact Hincl.
  - apply separated_sym. exact h21.
}

assert (HsepC: separated a7 i2 a5 x3).
{
  unfold separated, a7, a5.
  right. right. right. left.
  simpl. lia.
}

assert (HeqB: eqmem a6 A9 a3 x).
{
  intros q Hq.
  transitivity (a8 q).
  - exact (eqmem_memcpy a6 t3 a7 a3 a7 i2 x HsepB q Hq).
  - rewrite HA9. exact (eqmem_memcpy a8 t2 a7 a3 a7 i2 x HsepB q Hq).
}

assert (HeqA: eqmem a6 A9 a4 x1).
{
  intros q Hq.
  transitivity (a8 q).
  - exact (eqmem_memcpy a6 t3 a7 a4 a7 i2 x1 HsepA q Hq).
  - rewrite HA9. exact (eqmem_memcpy a8 t2 a7 a4 a7 i2 x1 HsepA q Hq).
}

assert (HeqC: eqmem a6 A9 a5 x3).
{
  intros q Hq.
  transitivity (a8 q).
  - exact (eqmem_memcpy a6 t3 a7 a5 a7 i2 x3 HsepC q Hq).
  - rewrite HA9. exact (eqmem_memcpy a8 t2 a7 a5 a7 i2 x3 HsepC q Hq).
}

assert (HeqA_pt: forall k:Z, (0 <= k)%Z -> (k < x1)%Z -> a6 (shift a4 k) = A9 (shift a4 k)).
{
  intros k Hk1 Hk2.
  apply HeqA. unfold included, a4. intro Hpos. simpl. repeat split; try reflexivity; lia.
}
assert (HeqB_pt: forall k:Z, (0 <= k)%Z -> (k < x)%Z -> a6 (shift a3 k) = A9 (shift a3 k)).
{
  intros k Hk1 Hk2.
  apply HeqB. unfold included, a3. intro Hpos. simpl. repeat split; try reflexivity; lia.
}

assert (Ea4: forall k:Z, shift a4 k = shift a k).
{ intro k. unfold a4, shift. simpl. f_equal. lia. }
assert (Ea3: forall k:Z, shift a3 k = shift a1 k).
{ intro k. unfold a3, shift. simpl. f_equal. lia. }

assert (HeqA_pt': forall k:Z, (0 <= k)%Z -> (k < x1)%Z -> a6 (shift a k) = A9 (shift a k)).
{ intros k Hk1 Hk2. rewrite <- (Ea4 k). apply HeqA_pt; assumption. }
assert (HeqB_pt': forall k:Z, (0 <= k)%Z -> (k < x)%Z -> a6 (shift a1 k) = A9 (shift a1 k)).
{ intros k Hk1 Hk2. rewrite <- (Ea3 k). apply HeqB_pt; assumption. }

assert (HDP: forall (to0 i0 K0 j0:Z) (res:R),
  (0 <= i0)%Z -> (i0 < i1)%Z -> (0 <= K0)%Z -> (K0 <= i)%Z ->
  (0 <= j0)%Z -> (j0 < i2)%Z -> (0 <= to0)%Z -> (to0 <= K0)%Z ->
  P_DotProduction a6 a a1 to0 i0 K0 j0 i2 res ->
  P_DotProduction A9 a a1 to0 i0 K0 j0 i2 res).
{
  intros to0 i0 K0 j0 res Hi0a Hi0b HK0a HK0b Hj0a Hj0b Hto0a Hto0b Hdp.
  induction Hdp.
  - apply Q_P_DotProduction_dotproduction_empty_range; assumption.
  - rewrite HeqA_pt' by nia.
    rewrite HeqB_pt' by nia.
    apply Q_P_DotProduction_dotproduction_positive_range.
    + assumption.
    + apply IHHdp; (assumption || nia).
}

assert (Ea5: forall k:Z, shift a5 k = shift a2 k).
{ intro k. unfold a5, shift. simpl. f_equal. lia. }

assert (HeqC_pt: forall k:Z, (0 <= k)%Z -> (k < x3)%Z -> a6 (shift a5 k) = A9 (shift a5 k)).
{
  intros k Hk1 Hk2.
  apply HeqC. unfold included, a5. intro Hpos. simpl. repeat split; try reflexivity; lia.
}
assert (HeqC_pt': forall k:Z, (0 <= k)%Z -> (k < x3)%Z -> a6 (shift a2 k) = A9 (shift a2 k)).
{ intros k Hk1 Hk2. rewrite <- (Ea5 k). apply HeqC_pt; assumption. }

assert (HRR: forall (to0 i0:Z),
  (0 <= i0)%Z -> (i0 < i3)%Z -> (0 <= to0)%Z -> (to0 <= i2)%Z ->
  P_RowResult a6 a a1 a2 to0 i0 i i2 ->
  P_RowResult A9 a a1 a2 to0 i0 i i2).
{
  intros to0 i0 Hi0a Hi0b Hto0a Hto0b Hrr.
  induction Hrr.
  - apply Q_P_RowResult_rowresult_empty; assumption.
  - apply Q_P_RowResult_rowresult_step.
    + assumption.
    + apply IHHrr; (assumption || nia).
    + rewrite <- HeqC_pt' by nia.
      apply HDP; (assumption || nia).
}

assert (HMR_gen: forall n:nat, forall m:Z, (Z.of_nat n = m)%Z -> (0 <= m)%Z -> (m <= i3)%Z ->
  P_MatrixResult a6 a a1 a2 m i i2 i1 ->
  P_MatrixResult A9 a a1 a2 m i i2 i1).
{
  induction n as [| n' IHn]; intros m Hnm Hma Hmb Hmr.
  - apply Q_P_MatrixResult_matrixresult_empty; lia.
  - inversion Hmr as [Mf0 A0 B0 C0 to0 K0 N0 M0 Hemp EQ0 | Mf0 A0 B0 C0 to0 K0 N0 M0 xdef Hpos Hrow Hmat EQ0].
    + lia.
    + apply Q_P_MatrixResult_matrixresult_step.
      * lia.
      * apply HRR.
        { lia. }
        { lia. }
        { lia. }
        { apply Z.le_refl. }
        { assumption. }
      * apply (IHn xdef); [lia | lia | lia | assumption].
}

assert (HMR: P_MatrixResult A9 a a1 a2 i3 i i2 i1).
{ apply (HMR_gen (Z.to_nat i3) i3); [lia | lia | lia | exact h24]. }

apply Q_P_MatrixResult_matrixresult_step.
- nia.
- replace (- (1) + (1 + i3))%Z with i3 by lia. exact h27.
- replace (- (1) + (1 + i3))%Z with i3 by lia. exact HMR.
Qed.

